spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

server:
  ssl:
    key-store: classpath:2549116_wx.qiouou.com.pfx
    key-store-password: I2hWa7Sm
    keyStoreType: PKCS12
  port: 443